"""init_user_biometrics_table

Revision ID: 6709d9ba42d6
Revises: 
Create Date: 2026-04-01 20:59:19.218486

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6709d9ba42d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('user_biometrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_biometrics_embedding_hnsw', 'user_biometrics', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_user_biometrics_external_user_id'), 'user_biometrics', ['external_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_biometrics_external_user_id'), table_name='user_biometrics')
    op.drop_index('ix_user_biometrics_embedding_hnsw', table_name='user_biometrics', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('user_biometrics')
    op.execute("DROP EXTENSION IF EXISTS vector;")
    # ### end Alembic commands ###
